version: "3"
volumes: 
  p12123db:
services:
  mssql:
    container_name: mssql
    image: "microsoft/mssql-server-linux:2017-CU13"
    volumes: 
      - p12123db:/var/opt/mssql/data
      - ./mssql:/mssql
      - ./mssql/odbc.ini:/etc/odbc.ini
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rd2019' -d Master -i /mssql/checkdb.sql
    environment:
      SA_PASSWORD: "P@ssw0rd2019"
      ACCEPT_EULA: "Y"
  dbaccess:
    container_name: dbaccess
    image: "msullivancm/dbaccess:20190520"
    volumes:
      - ./dbaccess/odbc.ini:/etc/odbc.ini
      - ./dbaccess/dbaccess.ini:/totvs/dbaccess/dbaccess.ini
    environment:
      - PENV = p12123
    ports: 
      - 7890:7890
    depends_on: 
      - mssql
      - p12123totvslic
  p12123totvslic:
    container_name: p12123totvslic
    image: "msullivancm/totvslic:20190427"
    ports: 
      - 5555:5555
      - 2234:2234
  p12123bin:
    container_name: p12123bin
    image: "msullivancm/p12123bin:20190520"
    volumes:
      - ./protheus_data:/totvs/protheus/protheus_data
    ports: 
      - 1234:1234
    depends_on: 
      - dbaccess
      - p12123totvslic
