USE [master];
GO
CREATE LOGIN siga 
    WITH PASSWORD    = N'msiga',
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO
EXEC sp_addsrvrolemember 
    @loginame = N'siga', 
    @rolename = N'sysadmin';
GO

CREATE DATABASE [p12123] ON  PRIMARY 
( NAME = N'p12123', FILENAME = N'/var/opt/mssql/data/p12123.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'p12123_log', FILENAME = N'/var/opt/mssql/data/p12123_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 COLLATE Latin1_General_BIN
GO
ALTER DATABASE [p12123] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [p12123] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [p12123] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [p12123] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [p12123] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [p12123] SET ARITHABORT OFF 
GO
ALTER DATABASE [p12123] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [p12123] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [p12123] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [p12123] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [p12123] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [p12123] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [p12123] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [p12123] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [p12123] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [p12123] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [p12123] SET  DISABLE_BROKER 
GO
ALTER DATABASE [p12123] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [p12123] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [p12123] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [p12123] SET  READ_WRITE 
GO
ALTER DATABASE [p12123] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [p12123] SET  MULTI_USER 
GO
ALTER DATABASE [p12123] SET PAGE_VERIFY CHECKSUM  
GO
USE [p12123]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [p12123] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
